// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VeloBid.Services.Auctions.Infrastructure.Persistence;

#nullable disable

namespace VeloBid.Services.Auctions.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AuctionsDbContext))]
    [Migration("20260529122926_InitialAuctionsDb")]
    partial class InitialAuctionsDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("auctions")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VeloBid.Services.Auctions.Domain.Aggregates.Auction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ActivatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("activated_at_utc");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset?>("ExpiredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expired_at_utc");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid")
                        .HasColumnName("seller_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<Guid?>("WinnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("winner_id");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "MinimumBidIncrement", "VeloBid.Services.Auctions.Domain.Aggregates.Auction.MinimumBidIncrement#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("minimum_bid_increment_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("minimum_bid_increment_currency");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Period", "VeloBid.Services.Auctions.Domain.Aggregates.Auction.Period#AuctionPeriod", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTimeOffset>("EndsAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("ends_at_utc");

                            b1.Property<DateTimeOffset>("StartsAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("starts_at_utc");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "StartingPrice", "VeloBid.Services.Auctions.Domain.Aggregates.Auction.StartingPrice#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("starting_price_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("starting_price_currency");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "WinningAmount", "VeloBid.Services.Auctions.Domain.Aggregates.Auction.WinningAmount#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("winning_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("winning_currency");
                        });

                    b.HasKey("Id");

                    b.ToTable("auctions", "auctions");
                });

            modelBuilder.Entity("VeloBid.Services.Auctions.Domain.Entities.Bid", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuctionId")
                        .HasColumnType("uuid")
                        .HasColumnName("auction_id");

                    b.Property<Guid>("BidderId")
                        .HasColumnType("uuid")
                        .HasColumnName("bidder_id");

                    b.Property<DateTimeOffset>("PlacedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("placed_at_utc");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Amount", "VeloBid.Services.Auctions.Domain.Entities.Bid.Amount#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("currency");
                        });

                    b.HasKey("Id");

                    b.HasIndex("AuctionId")
                        .HasDatabaseName("ix_bids_auction_id");

                    b.HasIndex("AuctionId", "PlacedAtUtc")
                        .HasDatabaseName("ix_bids_auction_id_placed_at_utc");

                    b.ToTable("bids", "auctions");
                });

            modelBuilder.Entity("VeloBid.Services.Auctions.Domain.Entities.Bid", b =>
                {
                    b.HasOne("VeloBid.Services.Auctions.Domain.Aggregates.Auction", null)
                        .WithMany("Bids")
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VeloBid.Services.Auctions.Domain.Aggregates.Auction", b =>
                {
                    b.Navigation("Bids");
                });
#pragma warning restore 612, 618
        }
    }
}
